#!/usr/local/bin/python3
# encoding: utf-8

import sys
import argparse
import speedtest
import logging
import logging.handlers

import units

class StderrHandler(logging.StreamHandler):
    def __init__(self):
        super().__init__()
        self.setFormatter(logging.Formatter('[%(process)d] %(message)s'))

class SyslogHandler(logging.handlers.SysLogHandler):
    def __init__(self, filename):
        super().__init__()
        self.setFormatter(logging.Formatter('%(levelname)s: %(name)s.%(funcName)s(): %(message)s'))

class FileHandler(logging.handlers.WatchedFileHandler):
    def __init__(self, filename):
        super().__init__(filename, encoding='utf-8')
        self.setFormatter(logging.Formatter('[%(asctime)s] [%(process)d] %(levelname)s: %(name)s.%(funcName)s(): %(message)s'))

logger = logging.getLogger('speedtest-cli').getChild(__name__)
logger.addHandler(StderrHandler())

class Option(object):
    def __init__(self):
        self.prog = 'speedtest-cli'
        parser = argparse.ArgumentParser(
            prog=self.prog,
            description=(
                'Command line interface for testing internet bandwidth using speedtest.net.\n'
                '--------------------------------------------------------------------------\n'
                'https://github.com/nkobayasi/speedtest-cli'))
        parser.add_argument('-v', '--version', action='store_true', help='Show the version number and exit')
        parser.add_argument('--no-download', action='store_false', dest='download', help='Do not perform download test')
        parser.add_argument('--no-upload', action='store_false', dest='upload', help='Do not perform upload test')
        parser.add_argument('--single', action='store_true', help='Only use a single connection instead of multiple. This simulates a typical file transfer.')
        parser.add_argument('--bytes', action='store_const', const=('byte', 8), default=('bit', 1), dest='units', help='Display values in bytes instead of bits. Does not affect the image generated by --share, nor output from --json or --csv')
        parser.add_argument('--share', action='store_true', help='Generate and provide a URL to the speedtest.net share results image, not displayed with --csv')
        parser.add_argument('--simple', action='store_true', help='Suppress verbose output, only show basic information')
        parser.add_argument('--csv', action='store_true', help='Suppress verbose output, only show basic information in CSV format. Speeds listed in bit/s and not affected by --bytes')
        parser.add_argument('--json', action='store_true', help='Suppress verbose output, only show basic information in JSON format. Speeds listed in bit/s and not affected by --bytes')
        parser.add_argument('--list', action='store_true', help='Display a list of speedtest.net servers sorted by distance')
        parser.add_argument('--server', action='append', type=int, default=[], help='Specify a server ID to test against. Can be supplied multiple times')
        parser.add_argument('--exclude', action='append', type=int, default=[], help='Exclude a server from selection. Can be supplied multiple times')
        parser.add_argument('--mini', action='store', help='URL of the Speedtest Mini server')
        parser.add_argument('--source', action='store', help='Source IP address to bind to')
        parser.add_argument('--timeout', action='store', default=10.0, type=float, help='HTTP timeout in seconds. Default %(default)s')
        parser.add_argument('--secure', action='store_true', help='Use HTTPS instead of HTTP when communicating with speedtest.net operated servers')
        parser.add_argument('--no-pre-allocate', action='store_false', dest='pre_allocate', help='Do not pre allocate upload data. Pre allocation is enabled by default to improve upload performance. To support systems with insufficient memory, use this option to avoid a MemoryError')
        parser.add_argument('-4', '--ipv4', action='store_true', help='Use IPv4')
        parser.add_argument('-6', '--ipv6', action='store_true', help='Use IPv6')
        parser.add_argument('-D', '--debug', action='store_true', help=argparse.SUPPRESS)
        self.args = parser.parse_args()

def main():
    logger.setLevel(logging.DEBUG)
    option = Option()
    if option.args.version:
        print('%s %s' % (option.prog, speedtest.__version__, ))
        print('Python %s' % (sys.version.strip(), ))
        return
    if option.args.debug:
        logging.getLogger('speedtest').setLevel(logging.DEBUG)
        logger.debug(option.args)

    testsuite = speedtest.TestSuite(option=option)
    if option.args.list:
        for server in sorted(testsuite.servers, key=lambda server: server.distance):
            supports = []
            if server.support_ipv4:
                supports.append('IPv4')
            if server.support_ipv6:
                supports.append('IPv6')
            print('%(id)5d) %(sponsor)s (%(name)s, %(country)s) %(support)s [%(distance)0.2fkm]' % {
                'id': server.id,
                'sponsor': server.sponsor,
                'name': server.name,
                'country': server.country,
                'support': ', '.join(supports),
                'distance': server.distance, })
        return
    if option.args.server:
        download = speedtest.DownloadResults()
        upload = speedtest.UploadResults()
        for server in map(lambda id: testsuite.servers.findById(id), option.args.server):
            download += server.download
            upload += server.upload
        print('Download: %s%s/s\nUpload: %s%s/s' % (
            units.Bandwidth(download.speed) / option.args.units[1], option.args.units[0],
            units.Bandwidth(upload.speed) / option.args.units[1], option.args.units[0], ))
        return
    if option.args.mini:
        server = speedtest.MiniServer(testsuite, url=option.args.mini)
        print('Download: %s%s/s\nUpload: %s%s/s' % (
            units.Bandwidth(server.download.speed) / option.args.units[1], option.args.units[0],
            units.Bandwidth(server.upload.speed) / option.args.units[1], option.args.units[0], ))
        return
    
    print(testsuite.server)
    
    if option.args.download:
        print('Download: %s%s/s' % (
            units.Bandwidth(testsuite.server.download.speed) / option.args.units[1], option.args.units[0], ))
    if option.args.upload:
        print('Upload: %s%s/s' % (
            units.Bandwidth(testsuite.server.upload.speed) / option.args.units[1], option.args.units[0], ))

    if option.args.simple:
        print('Ping: %fms\nDownload: %s%s/s\nUpload: %s%s/s' % (
            testsuite.results.server.latency,
            units.Bandwidth(testsuite.results.download.speed) / option.args.units[1], option.args.units[0],
            units.Bandwidth(testsuite.results.upload.speed) / option.args.units[1], option.args.units[0], ))
    elif option.args.csv:
        print(testsuite.results.csv())
    elif option.args.json:
        print(testsuite.results.json())

if __name__ == '__main__':
    main()